name: Deploy via FTP to Locaweb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ftp.miria-arquitetura.comercial.ws
          user: miria-arquitetur1
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./public
          remoteDir: /home/miria-arquitetur1/public_html
