name: Deploy via FTP to Locaweb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Generate Laravel optimized autoload files
        run: composer dump-autoload --optimize

      - name: Build Laravel assets (e.g., CSS, JS)
        run: npm install && npm run production

      - name: Upload files via FTP
        uses: wilspi/ftp-deploy-action@v2
        with:
          server: ftp.miria-arquitetura.comercial.ws
          username: miria-arquitetur1
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./public
          remote-dir: /home/miria-arquitetur1/public_html
